robot:
  arm:
    state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000 # update rate: 1000 Hz

    position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

    effort_controller:
      type: effort_controllers/JointGroupEffortController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
        