robot:
  arm:
    state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000 # update rate: 1000 Hz

    position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - shoulder_pan
        - shoulder_lift
        - elbow
        - wrist_1
        - wrist_2
        - wrist_3

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - shoulder_pan
        - shoulder_lift
        - elbow
        - wrist_1
        - wrist_2
        - wrist_3

    effort_controller:
      type: effort_controllers/JointGroupEffortController
      joints:
        - shoulder_pan
        - shoulder_lift
        - elbow
        - wrist_1
        - wrist_2
        - wrist_3
        